version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bloomberg_warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bloomberg_warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9000:8000"
    depends_on:
      - db


volumes:
  db-data: